# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optuna/protobuf/study.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from optuna.protobuf import pruners_pb2 as optuna_dot_protobuf_dot_pruners__pb2
from optuna.protobuf import samplers_pb2 as optuna_dot_protobuf_dot_samplers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='optuna/protobuf/study.proto',
  package='optuna.study',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1boptuna/protobuf/study.proto\x12\x0coptuna.study\x1a\x1doptuna/protobuf/pruners.proto\x1a\x1eoptuna/protobuf/samplers.proto\"v\n\x15SuggestUniformRequest\x12*\n\x05trial\x18\x01 \x01(\x0b\x32\x1b.optuna.study.TrialInstance\x12\x16\n\x0eparameter_name\x18\x02 \x01(\t\x12\x0b\n\x03low\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\" \n\x0fSuggestedDouble\x12\r\n\x05value\x18\x01 \x01(\x01\"O\n\x12\x46inishTrialRequest\x12*\n\x05trial\x18\x01 \x01(\x0b\x32\x1b.optuna.study.TrialInstance\x12\r\n\x05value\x18\x02 \x01(\x01\"O\n\x11PruneTrialRequest\x12*\n\x05trial\x18\x01 \x01(\x0b\x32\x1b.optuna.study.TrialInstance\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\xb8\x01\n\x12\x43reateStudyOptions\x12\x12\n\nstudy_name\x18\x01 \x01(\t\x12)\n\x07sampler\x18\x02 \x01(\x0b\x32\x18.optuna.samplers.Sampler\x12&\n\x06pruner\x18\x03 \x01(\x0b\x32\x16.optuna.pruners.Pruner\x12\x0f\n\x07storage\x18\x04 \x01(\t\x12*\n\tdirection\x18\x05 \x01(\x0e\x32\x17.optuna.study.Direction\"$\n\rStudyInstance\x12\x13\n\x0binstance_id\x18\x01 \x01(\x04\"\x07\n\x05\x45mpty\"M\n\rTrialInstance\x12*\n\x05study\x18\x01 \x01(\x0b\x32\x1b.optuna.study.StudyInstance\x12\x10\n\x08trial_id\x18\x02 \x01(\x05*\'\n\tDirection\x12\x0c\n\x08MINIMIZE\x10\x00\x12\x0c\n\x08MAXIMIZE\x10\x01\x32\xcf\x03\n\x05Study\x12O\n\x0c\x63reate_study\x12 .optuna.study.CreateStudyOptions\x1a\x1b.optuna.study.StudyInstance\"\x00\x12\x41\n\x0b\x63lose_study\x12\x1b.optuna.study.StudyInstance\x1a\x13.optuna.study.Empty\"\x00\x12I\n\x0bstart_trial\x12\x1b.optuna.study.StudyInstance\x1a\x1b.optuna.study.TrialInstance\"\x00\x12G\n\x0c\x66inish_trial\x12 .optuna.study.FinishTrialRequest\x1a\x13.optuna.study.Empty\"\x00\x12\x45\n\x0bprune_trial\x12\x1f.optuna.study.PruneTrialRequest\x1a\x13.optuna.study.Empty\"\x00\x12W\n\x0fsuggest_uniform\x12#.optuna.study.SuggestUniformRequest\x1a\x1d.optuna.study.SuggestedDouble\"\x00\x62\x06proto3')
  ,
  dependencies=[optuna_dot_protobuf_dot_pruners__pb2.DESCRIPTOR,optuna_dot_protobuf_dot_samplers__pb2.DESCRIPTOR,])

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='optuna.study.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MINIMIZE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXIMIZE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=737,
  serialized_end=776,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
MINIMIZE = 0
MAXIMIZE = 1



_SUGGESTUNIFORMREQUEST = _descriptor.Descriptor(
  name='SuggestUniformRequest',
  full_name='optuna.study.SuggestUniformRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trial', full_name='optuna.study.SuggestUniformRequest.trial', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter_name', full_name='optuna.study.SuggestUniformRequest.parameter_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='optuna.study.SuggestUniformRequest.low', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='optuna.study.SuggestUniformRequest.high', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=226,
)


_SUGGESTEDDOUBLE = _descriptor.Descriptor(
  name='SuggestedDouble',
  full_name='optuna.study.SuggestedDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='optuna.study.SuggestedDouble.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=260,
)


_FINISHTRIALREQUEST = _descriptor.Descriptor(
  name='FinishTrialRequest',
  full_name='optuna.study.FinishTrialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trial', full_name='optuna.study.FinishTrialRequest.trial', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='optuna.study.FinishTrialRequest.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=341,
)


_PRUNETRIALREQUEST = _descriptor.Descriptor(
  name='PruneTrialRequest',
  full_name='optuna.study.PruneTrialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trial', full_name='optuna.study.PruneTrialRequest.trial', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='optuna.study.PruneTrialRequest.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=422,
)


_CREATESTUDYOPTIONS = _descriptor.Descriptor(
  name='CreateStudyOptions',
  full_name='optuna.study.CreateStudyOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='study_name', full_name='optuna.study.CreateStudyOptions.study_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampler', full_name='optuna.study.CreateStudyOptions.sampler', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pruner', full_name='optuna.study.CreateStudyOptions.pruner', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage', full_name='optuna.study.CreateStudyOptions.storage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='optuna.study.CreateStudyOptions.direction', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=609,
)


_STUDYINSTANCE = _descriptor.Descriptor(
  name='StudyInstance',
  full_name='optuna.study.StudyInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='optuna.study.StudyInstance.instance_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=647,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='optuna.study.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=656,
)


_TRIALINSTANCE = _descriptor.Descriptor(
  name='TrialInstance',
  full_name='optuna.study.TrialInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='study', full_name='optuna.study.TrialInstance.study', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trial_id', full_name='optuna.study.TrialInstance.trial_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=735,
)

_SUGGESTUNIFORMREQUEST.fields_by_name['trial'].message_type = _TRIALINSTANCE
_FINISHTRIALREQUEST.fields_by_name['trial'].message_type = _TRIALINSTANCE
_PRUNETRIALREQUEST.fields_by_name['trial'].message_type = _TRIALINSTANCE
_CREATESTUDYOPTIONS.fields_by_name['sampler'].message_type = optuna_dot_protobuf_dot_samplers__pb2._SAMPLER
_CREATESTUDYOPTIONS.fields_by_name['pruner'].message_type = optuna_dot_protobuf_dot_pruners__pb2._PRUNER
_CREATESTUDYOPTIONS.fields_by_name['direction'].enum_type = _DIRECTION
_TRIALINSTANCE.fields_by_name['study'].message_type = _STUDYINSTANCE
DESCRIPTOR.message_types_by_name['SuggestUniformRequest'] = _SUGGESTUNIFORMREQUEST
DESCRIPTOR.message_types_by_name['SuggestedDouble'] = _SUGGESTEDDOUBLE
DESCRIPTOR.message_types_by_name['FinishTrialRequest'] = _FINISHTRIALREQUEST
DESCRIPTOR.message_types_by_name['PruneTrialRequest'] = _PRUNETRIALREQUEST
DESCRIPTOR.message_types_by_name['CreateStudyOptions'] = _CREATESTUDYOPTIONS
DESCRIPTOR.message_types_by_name['StudyInstance'] = _STUDYINSTANCE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TrialInstance'] = _TRIALINSTANCE
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuggestUniformRequest = _reflection.GeneratedProtocolMessageType('SuggestUniformRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTUNIFORMREQUEST,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.SuggestUniformRequest)
  ))
_sym_db.RegisterMessage(SuggestUniformRequest)

SuggestedDouble = _reflection.GeneratedProtocolMessageType('SuggestedDouble', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTEDDOUBLE,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.SuggestedDouble)
  ))
_sym_db.RegisterMessage(SuggestedDouble)

FinishTrialRequest = _reflection.GeneratedProtocolMessageType('FinishTrialRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINISHTRIALREQUEST,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.FinishTrialRequest)
  ))
_sym_db.RegisterMessage(FinishTrialRequest)

PruneTrialRequest = _reflection.GeneratedProtocolMessageType('PruneTrialRequest', (_message.Message,), dict(
  DESCRIPTOR = _PRUNETRIALREQUEST,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.PruneTrialRequest)
  ))
_sym_db.RegisterMessage(PruneTrialRequest)

CreateStudyOptions = _reflection.GeneratedProtocolMessageType('CreateStudyOptions', (_message.Message,), dict(
  DESCRIPTOR = _CREATESTUDYOPTIONS,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.CreateStudyOptions)
  ))
_sym_db.RegisterMessage(CreateStudyOptions)

StudyInstance = _reflection.GeneratedProtocolMessageType('StudyInstance', (_message.Message,), dict(
  DESCRIPTOR = _STUDYINSTANCE,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.StudyInstance)
  ))
_sym_db.RegisterMessage(StudyInstance)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.Empty)
  ))
_sym_db.RegisterMessage(Empty)

TrialInstance = _reflection.GeneratedProtocolMessageType('TrialInstance', (_message.Message,), dict(
  DESCRIPTOR = _TRIALINSTANCE,
  __module__ = 'optuna.protobuf.study_pb2'
  # @@protoc_insertion_point(class_scope:optuna.study.TrialInstance)
  ))
_sym_db.RegisterMessage(TrialInstance)



_STUDY = _descriptor.ServiceDescriptor(
  name='Study',
  full_name='optuna.study.Study',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=779,
  serialized_end=1242,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_study',
    full_name='optuna.study.Study.create_study',
    index=0,
    containing_service=None,
    input_type=_CREATESTUDYOPTIONS,
    output_type=_STUDYINSTANCE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='close_study',
    full_name='optuna.study.Study.close_study',
    index=1,
    containing_service=None,
    input_type=_STUDYINSTANCE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='start_trial',
    full_name='optuna.study.Study.start_trial',
    index=2,
    containing_service=None,
    input_type=_STUDYINSTANCE,
    output_type=_TRIALINSTANCE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finish_trial',
    full_name='optuna.study.Study.finish_trial',
    index=3,
    containing_service=None,
    input_type=_FINISHTRIALREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='prune_trial',
    full_name='optuna.study.Study.prune_trial',
    index=4,
    containing_service=None,
    input_type=_PRUNETRIALREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='suggest_uniform',
    full_name='optuna.study.Study.suggest_uniform',
    index=5,
    containing_service=None,
    input_type=_SUGGESTUNIFORMREQUEST,
    output_type=_SUGGESTEDDOUBLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUDY)

DESCRIPTOR.services_by_name['Study'] = _STUDY

# @@protoc_insertion_point(module_scope)
