# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# flake8: noqa
import grpc

from optuna.protobuf import study_pb2 as optuna_dot_protobuf_dot_study__pb2


class StudyStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.create_study = channel.unary_unary(
            '/optuna.study.Study/create_study',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.CreateStudyOptions.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.FromString,
        )
        self.close_study = channel.unary_unary(
            '/optuna.study.Study/close_study',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.Empty.FromString,
        )
        self.start_trial = channel.unary_unary(
            '/optuna.study.Study/start_trial',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.TrialInstance.FromString,
        )
        self.finish_trial = channel.unary_unary(
            '/optuna.study.Study/finish_trial',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.FinishTrialRequest.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.Empty.FromString,
        )
        self.prune_trial = channel.unary_unary(
            '/optuna.study.Study/prune_trial',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.PruneTrialRequest.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.Empty.FromString,
        )
        self.suggest_uniform = channel.unary_unary(
            '/optuna.study.Study/suggest_uniform',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.SuggestUniformRequest.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.SuggestedDouble.FromString,
        )
        self.best_params = channel.unary_unary(
            '/optuna.study.Study/best_params',
            request_serializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.SerializeToString,
            response_deserializer=optuna_dot_protobuf_dot_study__pb2.BestParams.FromString,
        )


class StudyServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def create_study(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_study(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_trial(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def finish_trial(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def prune_trial(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def suggest_uniform(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def best_params(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudyServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'create_study': grpc.unary_unary_rpc_method_handler(
            servicer.create_study,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.CreateStudyOptions.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.SerializeToString,
        ),
        'close_study': grpc.unary_unary_rpc_method_handler(
            servicer.close_study,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.Empty.SerializeToString,
        ),
        'start_trial': grpc.unary_unary_rpc_method_handler(
            servicer.start_trial,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.TrialInstance.SerializeToString,
        ),
        'finish_trial': grpc.unary_unary_rpc_method_handler(
            servicer.finish_trial,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.FinishTrialRequest.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.Empty.SerializeToString,
        ),
        'prune_trial': grpc.unary_unary_rpc_method_handler(
            servicer.prune_trial,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.PruneTrialRequest.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.Empty.SerializeToString,
        ),
        'suggest_uniform': grpc.unary_unary_rpc_method_handler(
            servicer.suggest_uniform,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.SuggestUniformRequest.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.SuggestedDouble.SerializeToString,
        ),
        'best_params': grpc.unary_unary_rpc_method_handler(
            servicer.best_params,
            request_deserializer=optuna_dot_protobuf_dot_study__pb2.StudyInstance.FromString,
            response_serializer=optuna_dot_protobuf_dot_study__pb2.BestParams.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'optuna.study.Study', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
