# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optuna/protobuf/trial.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='optuna/protobuf/trial.proto',
  package='optuna.trial',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1boptuna/protobuf/trial.proto\x12\x0coptuna.trial\"\x07\n\x05Trialb\x06proto3')
)




_TRIAL = _descriptor.Descriptor(
  name='Trial',
  full_name='optuna.trial.Trial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Trial'] = _TRIAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trial = _reflection.GeneratedProtocolMessageType('Trial', (_message.Message,), dict(
  DESCRIPTOR = _TRIAL,
  __module__ = 'optuna.protobuf.trial_pb2'
  # @@protoc_insertion_point(class_scope:optuna.trial.Trial)
  ))
_sym_db.RegisterMessage(Trial)


# @@protoc_insertion_point(module_scope)
